Repository growth-genius/travel-group-service, pull requests merged in 2023-06, with the labels that each got.

#6 TravelGroup,TravelGroupMember 기능 조건 컬럼 전체 변경
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/TravelGroupController.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/TravelGroupJoinController.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/TravelGroupMemberController.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/FcmContentDto.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/TravelGroupDto.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/TravelGroupMemberDto.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/entity/TravelGroup.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/entity/TravelGroupMember.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepository.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryImpl.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryQuerydsl.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/service/TravelGroupJoinService.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/service/TravelGroupMemberService.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/service/TravelGroupService.java
  src/test/java/com/gg/tgather/travelgroupservice/modules/group/TravelGroupJoinControllerTest.java
  src/test/java/com/gg/tgather/travelgroupservice/modules/group/kafka/TravelGroupKafkaTest.java
  src/test/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryImplTest.java
  src/test/java/com/gg/tgather/travelgroupservice/modules/group/service/TravelGroupJoinServiceTest.java
  src/test/java/com/gg/tgather/travelgroupservice/modules/group/service/TravelGroupMemberServiceTest.java
Labels: 📬 API, 🐞 BugFix

#8 Seunggu/search travel group by me
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/controller/TravelGroupController.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/controller/TravelGroupJoinController.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/controller/TravelGroupMemberController.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/TravelGroupDto.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/TravelGroupMemberDto.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryImpl.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/repository/TravelGroupRepositoryQuerydsl.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/service/TravelGroupService.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/vo/TravelGroupSearchVo.java
Labels: ✨ Feature

#10 fix: 주소 변경
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/controller/TravelGroupController.java
Labels: 🐞 BugFix

#11 refactor: travel-group prefix 제거
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/controller/TravelGroupController.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/controller/TravelGroupJoinController.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/controller/TravelGroupMemberController.java
Labels: 🔨 Refactor

#12 feat: requestmapping 추가
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/controller/TravelGroupController.java
Labels: 🐞 BugFix

#14 feature : 여행그룹 전체 조회
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/controller/TravelGroupController.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/TravelGroupWithPageable.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/service/TravelGroupService.java
Labels: ✨ Feature

#15 fix : 중복된 URI 수정
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/controller/TravelGroupController.java
Labels: 🐞 BugFix

#16 여행그룹 CRUD 누락필드 추가
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/TravelGroupDto.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/entity/TravelGroup.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/form/TravelGroupModifyForm.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/form/TravelGroupSaveForm.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/service/TravelGroupMemberService.java
  src/test/java/com/gg/tgather/travelgroupservice/modules/group/TravelGroupJoinControllerTest.java
Labels: 🐞 BugFix

#17 feat : 여행그룹 추가시 멤버 닉네임 프로필 명 추가
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/controller/TravelGroupMemberController.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/TravelGroupDto.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/dto/TravelGroupMemberDto.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/entity/TravelGroupMember.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/form/TravelGroupJoinForm.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/form/TravelGroupSaveForm.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/service/TravelGroupMemberService.java
  src/main/java/com/gg/tgather/travelgroupservice/modules/group/service/TravelGroupService.java
  src/test/java/com/gg/tgather/travelgroupservice/modules/group/TravelGroupJoinControllerTest.java
  src/test/java/com/gg/tgather/travelgroupservice/modules/group/form/TravelGroupJoinTestForm.java
  src/test/java/com/gg/tgather/travelgroupservice/modules/group/kafka/TravelGroupKafkaTest.java
  src/test/java/com/gg/tgather/travelgroupservice/modules/group/service/TravelGroupJoinServiceTest.java
  src/test/java/com/gg/tgather/travelgroupservice/modules/group/service/TravelGroupMemberServiceTest.java
Labels: ✨ Feature
